config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  resources :friends
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "chats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user

  attr_accessor :message 

  def message=(message)
      messages = [
        { 'role' => 'system', 'content' => message }
      ]
      
      q_and_a.each do |question, answer| 
        messages << { 'role' => 'user', 'content' => question }
        messages << { 'role' => 'assistant', 'content' => answer }
      end
    
    response_raw = client.chat(
      parameters: {
        model: 'gpt-3.5-turbo',
        messages:,
        temperature: 0.7,
        max_tokens: 500,
        top_p: 1
      }
    )

    self.history = { 'history' => [] } if history.blank?
    self.history['history'] << response_raw 

    #Rails.logger.debug response_raw
    response = JSON.parse(response_raw.to_json, object_class: OpenStruct)
    self.q_and_a << [message, response.choices[0].message.content]
    
  end

  private 

  def client
    OpenAI::Client.new
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = Chat.none 
    if current_user.chats.any?
      redirect_to chat_url(current_user.chats.last)
    end
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(user_id: current_user.id)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully created." }
        format.json { render :show, status: :created, location: @chat }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
        format.turbo_stream

      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy!

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:message)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :age)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
    def list_name(chat)
        if chat.q_and_a.present?
            chat.q_and_a.first[0].truncate(20)
        else 
            "Chat #{chat.id}"
        end
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chats/_chat.html.erb
<turbo-frame id="current-chat">
  <div id="<%= dom_id chat %>" class="container-fluid vh-75">
    <div id="history-area" class="h-100">
      <% unless chat.q_and_a.blank? %>
        <% chat.q_and_a.each do |question, answer| %>
          <div class="row mb-2">
            <div class="col-md-1">
              You
            </div>
            <div class="col">
              <%= simple_format question %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-1">
              OpenAI
            </div>
            <div class="col">
              <%= simple_format answer %>
            </div>
          </div>


        <% end %>
        
      <% end %>
      
    </div>

  </div>
  <%= form_with(model: chat) do |form| %>
    <div class="input-group mb-3">
      <%= form.text_field :message, placeholder: 'send a message', class: 'form-control' %>
      <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
        <i class="fa fa-paper-plane"></i>
      </button>
    </div>
  <% end %>

</turbo-frame>

app/views/chats/_chat_list.html.erb
<div class="row w-100 border-bottom text-white">
    <div class="col-md-10 text-white">
        <%= link_to chat_list, data: { turbo_frame: "_top" } do %>
            <i class="fa fa-message"></i> <%= list_name(chat_list) %>
        <% end %>
    </div>
    <div class="col-md-1 text-white">
        <%= button_to @chat, methode: :delete, data: { turbo_frame: "_top" }, 
                class: "border-none btn btn-dark pt-0" do %>
            <i class="fa fa-trash"></i>
        <% end %>
    </div>
</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :history, style: "display: block" %>
    <%= form.text_field :history %>
  </div>

  <div>
    <%= form.label :q_and_a, style: "display: block" %>
    <%= form.text_field :q_and_a %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/create.turbo_stream.erb
<%= turbo_stream.prepend "user-chats", partial: "chats/chat_list", locals: {chat_list: @chat} %>
<%= turbo_stream.replace "current-chat", partial: "chats/chat", locals: { chat: @chat} %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>
You dont have any chats yet. Create one by clicking 

<%= form_with(model: Chat.new) do |form| %>
  <%= form.submit 'Here', class: 'btn btn-dark border-light' %>
<% end %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat %>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= friend.age %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsopenai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script defer src="https://kit.fontawesome.com/052cfc60bd.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid d-flex vh-100">
      <div class="row align-self-stretch w-100">
        <div class="col-md-2 mx-auto bg-dark text-white">
          <div class="w-100 text-align-center d-flex justifiy-content-center mt-3">
            <%= form_with(model: Chat.new) do |form| %>
              <%= form.submit '+ New Chat', class: 'btn btn-dark border-light' %>
            <% end %>
          </div>
          <div class="mt-3">
            <h4>Today</h4>
            <turbo-frame id="user-chats">
              <%= render partial: 'chats/chat_list', collection: current_user.chats.reverse if current_user &&  current_user.chats %>
            </turbo-frame>
          </div>

        </div>
        <div class="col-10">
          <%= yield %>        
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<%= link_to  "chats", chats_path %>